### ISSUE TITLE
Open as tab(s) crashes and fails to create new tab if default URL is not set for container

### ISSUE THREAD

**Issue by mrzzy** [charles-m-knox/firefox-containers-helper#27]
### Background
Firefox: 89.0.2 (64-bit)
Addon Version: 0.0.19.

### Problem
When attempting to open a new container tab by clicking the container or pressing enter, nothing happens.

Opening the console, the following error is observed when clicking the container tab / pressing enter.

```
Uncaught TypeError: urlToOpen is undefined
    openMultipleContexts moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js line 733 > srcScript:733
    openMultipleContexts moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js line 733 > srcScript:731
    containerClickHandler moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js line 733 > srcScript:1123
    applyEventListenersToContainerListItem moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js line 733 > srcScript:446
    openMultipleContexts moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js:733
    openMultipleContexts moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js:731
    containerClickHandler moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js:1123
    applyEventListenersToContainerListItem moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js:446
    applyEventListenersToContainerListItem moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js:445
    buildContainerListItem moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js:513
    filterContainers moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js:1227
    filterContainers moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js:1223
    promise callback*filterContainers moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js:1212
    initializeDocument moz-extension://d6f275ec-6c91-46fb-9a95-7ad7ac1dc084/context.js:1386
context.js line 733 > srcScript:733:17
```

Using the console I can observe that:
- `contextToOpenAsContainer.cookieStoreId` is `"firefox-container-1429"`
- `config.containerDefaultUrls` is an empty object (`{}`).
- As a result `urlToOpen` is undefined, the corresponding call to `urlToOpen.indexOf()` introduced in 3bf71650 is thus expected to error.

### Proposed Fix
Handle the case where `urlToOpen` is `null` in `openMultipleContexts()` to open a empty container tab with no default URL set
to fix the bug introduced in 3bf71650.

**Comment by charles-m-knox** [comment]
Hi @mrzzy,

Thank you so much for the detailed bug report. Sorry for introducing this bug. I'll get this fixed right away. Expect a release in the next 2-3 hrs tops.

**Comment by charles-m-knox** [comment]
Ok, I think I've got it fixed on my local setup. Doing a bit of testing right now.

**Comment by charles-m-knox** [comment]
@mrzzy This has been fixed in [`v0.0.20`](https://github.com/charles-m-knox/firefox-containers-helper/releases/tag/v0.0.20). The add-on is released on the Mozilla Addon store here: https://addons.mozilla.org/en-US/firefox/addon/containers-helper/

You probably already know this, but just in case it helps - to update the extension manually, you can go to your Firefox addon settings and click the settings gear, and update your addons like this to receive the fixed extension:

![Screenshot-20210916065939-482x279](https://user-images.githubusercontent.com/8022749/133625829-4c9098c8-5d08-402e-9309-6a4295136514.png)

Thanks again for creating the issue. I really apologize for creating the regression in 3bf7165. As this extension matures, I intend to implement unit tests and make it more robust, so that this sort of thing doesn't happen again.

Please, let me know if you run into anything else, or if the issue still doesn't appear to be resolved for you!

**Comment by charles-m-knox** [comment]
Closing this for now, but if you run into anything, I'll re-open.

**Comment by mrzzy** [comment]
It works now. Thanks for the effort :+1:
